### ISSUE TITLE
New validation

### ISSUE THREAD

**Issue by KevinGeLe** [BhaskarPanja93/View-Bot-Client#23]
Moved from CAPTCHA to click on an image.
![image](https://user-images.githubusercontent.com/125448701/226929388-6405e3d6-1a3a-451b-8c31-83da03e7f2bf.png)
The only way I can see to get around to is to get a screenshot, proompt it to GPT4 over API and then have it respond 1-4 where 1 is the most left and 4 the most right.

**Comment by KevinGeLe** [comment]
Looks like the free ChatGPT API that I used have been flagged and there is currently been working on getting it up and running. The API is also the premium which have the Image thing. I have made the code that takes a screenshot, upload it to Imgur and then use that link in ChatGPT, so it can figure out which one is correct (around 80% accuracy.) 

Also Windscribe only has 116 locations and I already have 200 clicks, doesnt it detect the ip and flag it as a botting?

**Comment by BhaskarPanja93** [comment]
![cloud](https://user-images.githubusercontent.com/101955196/227737951-7e5c88b0-6d56-449c-a20d-2eb5112a3527.PNG)
![cube](https://user-images.githubusercontent.com/101955196/227737952-142ed5a1-9f27-4cf8-be0e-6c93cab612d6.PNG)
![flag](https://user-images.githubusercontent.com/101955196/227737953-ad3fa824-0731-4d4a-aca3-651252d6fe8d.PNG)
![girl](https://user-images.githubusercontent.com/101955196/227737954-d1c08424-b007-4860-a77a-b84242c1d9e8.PNG)
![heart](https://user-images.githubusercontent.com/101955196/227737955-4b3ea0ba-5832-4225-bbc8-86819b88ecaf.PNG)
![lightning](https://user-images.githubusercontent.com/101955196/227737956-b4f8f083-8291-4205-844a-b0e26198b02f.PNG)
![moon](https://user-images.githubusercontent.com/101955196/227737957-9a29a513-0492-4e15-99dd-e7220a12de52.PNG)
![paint brush](https://user-images.githubusercontent.com/101955196/227737959-83b3fd03-b147-49fa-b45c-ddcd776d4cfe.PNG)
![paper](https://user-images.githubusercontent.com/101955196/227737960-cbadde76-9009-44e4-949d-d2651d66e6c7.PNG)
![pencil](https://user-images.githubusercontent.com/101955196/227737961-f2108104-a280-4ae6-a03a-a5eef09448d7.PNG)
![picture](https://user-images.githubusercontent.com/101955196/227737962-551f21ad-2a2a-4e40-b690-1ffd576808db.PNG)
![printer](https://user-images.githubusercontent.com/101955196/227737964-163705af-e21e-4650-915c-d1fa7d3bbb43.PNG)
![puzzle piece](https://user-images.githubusercontent.com/101955196/227737965-e32679f9-1f04-42bb-a5ff-c919e660b584.PNG)
![smartphone](https://user-images.githubusercontent.com/101955196/227737966-78fecd67-07d8-4add-945e-e63d2c829457.PNG)
![snowflake](https://user-images.githubusercontent.com/101955196/227737969-cc0ec346-b278-4155-81c8-f607541f241c.PNG)
![square](https://user-images.githubusercontent.com/101955196/227737970-752fbbe4-0d35-481f-b015-f55b8509efc9.PNG)
![star](https://user-images.githubusercontent.com/101955196/227737972-6a7b08a3-ad14-455a-9404-006b613dc8c8.PNG)
![sun](https://user-images.githubusercontent.com/101955196/227737973-fce2530b-a16d-4229-a331-ac89d9452b8c.PNG)
![tree](https://user-images.githubusercontent.com/101955196/227737975-881664a7-57f2-41db-b967-a870be84352b.PNG)
![truck](https://user-images.githubusercontent.com/101955196/227737976-39d0a985-311a-4b82-be47-250f7f41c047.PNG)
![umbrella](https://user-images.githubusercontent.com/101955196/227737977-7282ef6f-ab76-4e92-83d4-94be42df40b7.PNG)
@KevinGeLe i dont know if i am doing something really stupid.... Okay so as of now, i am taking screenshots of all the images (of the new captcha system) and telling the code which one is what, so later when that particular object has to be searched, it will ask for the learnt word image and click on it. If it cant understand any object, it takes a screenshot and sends it to server, and then i will manually tell it what it means, so it will work next time onwards.

So far i collected 28 names of individual objects:
![airplane](https://user-images.githubusercontent.com/101955196/227737939-5f16067d-2cf8-49ff-aa81-21257f0a2c76.PNG)
![basket](https://user-images.githubusercontent.com/101955196/227737942-cce7f0ab-de21-424f-948c-984c6061c46b.PNG)
![boy](https://user-images.githubusercontent.com/101955196/227737943-cbc424d6-ff0f-4549-856d-c7e23cea67f9.PNG)
![brush](https://user-images.githubusercontent.com/101955196/227737946-d3ac43e5-8e36-473a-b17a-db7999e46cf7.PNG)
![building](https://user-images.githubusercontent.com/101955196/227737947-e0c1aa64-682a-4572-a82b-a346521dbda0.PNG)
![camera](https://user-images.githubusercontent.com/101955196/227737948-3a5ffada-5315-49aa-9064-8eb33bd05b16.PNG)
![circle](https://user-images.githubusercontent.com/101955196/227737950-e9be6e9f-7fa3-4a4c-9e33-b22fda618bea.PNG)

**Comment by KevinGeLe** [comment]
Thats actually genius, most of them is the same anyway. Its just like when labeling for NLP eg. Products and measurements.

Also in what part of the server is the bot that is clicking on the images, because it could be optimized alot and I have used opencv and pyautogui before, so I could come up with some improvements and make a pull request.

@BhaskarPanja93

**Comment by BhaskarPanja93** [comment]
No no you guessed it right, i wont make combinations, i will just see what image it wants and search the single image, not combination of all 4, that would be stupid.
I will make this part kf the code in 2-3 days, need some time, i am stuck with college.

And the main bot clicking part is in the (server side) v4/linkvertise/stable/ngrok_direct.py, i made it efficient enough, till the point the code knows what image to find next, and only searches those.
@KevinGeLe

**Comment by KevinGeLe** [comment]
> No no you guessed it right, i wont make combinations, i will just see what image it wants and search the single image, not combination of all 4, that would be stupid. I will make this part kf the code in 2-3 days, need some time, i am stuck with college.
> 
> And the main bot clicking part is in the (server side) v4/linkvertise/stable/ngrok_direct.py, i made it efficient enough, till the point the code knows what image to find next, and only searches those. @KevinGeLe

The example is done. I will try to make a pull request with it in.
[validate.zip](https://github.com/BhaskarPanja93/View-Bot-Client/files/11070403/validate.zip)

@BhaskarPanja93

**Comment by BhaskarPanja93** [comment]
Yes i planned to do the exact thing, except that instead of pytesseract, i will keep images of the sentence.PNG and check which sentence appeared, and then find the image accordingly, lets see what is more efficient (with or without the tesseract), because again installing tessaract is a hassle everyone has to go through.

Also thanks for splitting all images for me, i had a busy weekend so took a break from this project.
@KevinGeLe

**Comment by BhaskarPanja93** [comment]
okay, i almost made the code so tesseract doesnt need to be installed, instead the package directory will be copied from server to VM automatically and then i modified the original pytesseract code to include the new folder as the binary path, so we dont need to add the folder to PATH. i need 1 more day to make sure things work.

**Comment by BhaskarPanja93** [comment]
okay, i almost made the code so tesseract doesnt need to be installed, instead the package directory will be copied from server to VM automatically and then i modified the original pytesseract code to include the new folder as the binary path, so we dont need to add the folder to PATH. i need 1 more day to make sure things work.

**Comment by KevinGeLe** [comment]
It looks like it takes a screenshot, but then just skips and goes to looping through the rest. 
Also its to quick to continue from resseting Chrome as it just continues without clicking the reset button. So either make it so that the wait is a fixed number or have it check to see if its done and then continue.

@BhaskarPanja93

**Comment by KevinGeLe** [comment]
The Ngrok account is also being rate limited.

@BhaskarPanja93

**Comment by KevinGeLe** [comment]
> The Ngrok account is also being rate limited.
> 
> @BhaskarPanja93

It is because Linkvertise just updated how to complete the offer, so the program just timeouts and keeps sending requests to the server till it ends up getting rate limited.

**Comment by BhaskarPanja93** [comment]
Okay back to work, i have 2 days to finish all problems, and i will. Lets start afresh.
@KevinGeLe

**Comment by KevinGeLe** [comment]
I think I know how the code works now. Have spent most of my time understanding it.

![image](https://user-images.githubusercontent.com/125448701/229293476-ca248915-0ae6-48eb-86ee-176ef694180c.png)
It is caused by the globe not being found as it havent been added to .png, also if the image wasnt found after a number of times then stop it from sending new requests. Should stop the rate limit.

edit:
Globe:
[Had to use imgur as Github didnt give me permissions to upload](https://imgur.com/a/36N06cj)



@BhaskarPanja93

**Comment by BhaskarPanja93** [comment]
I made some massive changes to the code, so it works with the new layout of Linkvertise. I updated the server to check if the new code works. I will push to github soon. Also regarding the "Rate Limit", I am making a totally new version of network transfers, totally using sockets, all requests and everything will be done via sockets, the only purpose of WebPage will be just to get the final page after linkvertise ad viewing is done. So it will reduce the number of connections made to server, and instead reuse the same (scalable) socket connection (you can find the test codes in the server's /test directory), also yes, i am adding the "Globe" Image.
@KevinGeLe

**Comment by BhaskarPanja93** [comment]
All work done i guess, code is functional, as of now. if new problem occurs, feel free to create a new issue.

**Comment by SiisMax999** [comment]
> > No no you guessed it right, i wont make combinations, i will just see what image it wants and search the single image, not combination of all 4, that would be stupid. I will make this part kf the code in 2-3 days, need some time, i am stuck with college.
> > And the main bot clicking part is in the (server side) v4/linkvertise/stable/ngrok_direct.py, i made it efficient enough, till the point the code knows what image to find next, and only searches those. @KevinGeLe
> 
> The example is done. I will try to make a pull request with it in. [validate.zip](https://github.com/BhaskarPanja93/View-Bot-Client/files/11070403/validate.zip)
> 
> Edit: I have 28 items, I havent ran into anymore so I think I counted wrong. It works by taking a screen shot of the "Please validate that you are not a robot:" and taken the text under at the same time. Use tesseract to get the text and only use the last word and remove the punctuation and serve it directly as a {item}.png.
> 
> @BhaskarPanja93

How do I use it to add tampermonkey on a browser
