### ISSUE TITLE
can you help me?

### ISSUE THREAD

**Issue by Rayan68100** [BhaskarPanja93/View-Bot-Client#29]
hi, i watched your videos and i did the same as you, when i run the script it fails at the chrome stage. it says the site can't be reached https’s server IP address could not be found.
scrolling 0*0 for ngrok_visit_site

scrolling 0*0 for ngrok_direct_open
cookie_accept: webpage_opened: True
unsolvable_captcha: webpage_opened: True
captcha: webpage_opened: True
linkvertise_top: webpage_opened: True
discover_articles: webpage_opened: True
close_articles: webpage_opened: True
pre_special_ad: webpage_opened: True
special_ad_processing: webpage_opened: True
waiting_big_ad: webpage_opened: True
post_big_ad: webpage_opened: True
final_go_to_website: webpage_opened: True
yt_reached: webpage_opened: True

scrolling 0*0 for
sleeping 5 for blank_chrome
and it repeat over and over again, also, i have another captcha -> https://imgur.com/1FM62oe

**Comment by KevinGeLe** [comment]
We are working on it right now (: [#29](https://github.com/BhaskarPanja93/View-Bot-Client/issues/23)

**Comment by BhaskarPanja93** [comment]
@Rayan68100 
 site can't be reached is a temporary issue, most probably your internet is slow, so it is unable to use connection, please check if you have a stable internet, and it will work normally.

And the other CAPTCHA, we are working on it, just give a few days, and it will be working again.

**Comment by BhaskarPanja93** [comment]
Code has been updated, you can use it as usual again. No user-interaction needed to update code (updation process is automatic)

**Comment by DartMouthWrld** [comment]
I have the same issue, chrome opens up but nothing happens after, vm_main.py seems to be stuck in a loop @BhaskarPanja93 @KevinGeLe
