### ISSUE TITLE
After first view it wont continue until the vm restarts.

### ISSUE THREAD

**Issue by KevinGeLe** [BhaskarPanja93/View-Bot-Client#35]
After its done with the first view it wont clear the browser, nor will it continue to Linkvertise. It just loops through and tries to locate Ngrok to Linkvertise. Then because it couldnt find anything, it restarts.
**[Imgur](https://imgur.com/Ca5fgmz)**
Chrome_blank and Chrome_restore is both false, suggesting that on loop it skips this step.

Also I requested a payout on Linkvertise today. I had some problem with my ip being banned, so I had to use a vpn to request it. Not sure why though. 
![image](https://user-images.githubusercontent.com/125448701/229366045-5c05e88e-bc6a-48dc-abce-5ee6ea19e6de.png)

@BhaskarPanja93

**Comment by BhaskarPanja93** [comment]
@KevinGeLe 
Is this loop issue before today's commit or after?
Good luck with your payout, hopefully everything works.

**Comment by KevinGeLe** [comment]
> @KevinGeLe Is this loop issue before today's commit or after? Good luck with your payout, hopefully everything works.

Its after it gets one view 3 minutes in on the dashboard, it is stuck that way, but then restarts at around 8-9 minute mark. (I have also tried on another computer), also a few times the clear history doesnt have time enough to clear.


EDIT: I had to delete the files on the vm and then let it get them again and now it doesnt restart after 5 minutes of doing a view/nothing. But even on first start 50/50 Chrome_blank and Chrome_restore is both false and it just waits till restart. 

If adding so that Chrome_blank and Chrome_restore needs to be true before continuing will make sure, that chrome was opened and ready perform the view, instead of just continue the viewing if it havent even went onto ngrok to get the Linkvertise link.

New edit:
[And all my screenshot cant be uploaded for some reason](https://ibb.co/3SGLxWt)


@BhaskarPanja93

**Comment by KevinGeLe** [comment]
> > @KevinGeLe Is this loop issue before today's commit or after? Good luck with your payout, hopefully everything works.
> 
> Its after it gets one view 3 minutes in on the dashboard, it is stuck that way, but then restarts at around 8-9 minute mark. (I have also tried on another computer), also a few times the clear history doesnt have time enough to clear.
> 
> EDIT: I had to delete the files on the vm and then let it get them again and now it doesnt restart after 5 minutes of doing a view/nothing. But even on first start 50/50 Chrome_blank and Chrome_restore is both false and it just waits till restart.
> 
> If adding so that Chrome_blank and Chrome_restore needs to be true before continuing will make sure, that chrome was opened and ready perform the view, instead of just continue the viewing if it havent even went onto ngrok to get the Linkvertise link.
> 
> New edit: [And all my screenshot cant be uploaded for some reason](https://ibb.co/3SGLxWt)
> 
> @BhaskarPanja93

Stupidity hit me hard. 
I have to have the vm window open, because the mouse wont be captured if its in headless mode. So I have to start it in headless, open the vm window, then wait till the chrome window have opened, click on the search bar and then close vm window. 

Its not a fault with the code but rather the mechanics of VirtualBox, I will look into it, maybe all we need is a script that acts as a real mouse and then shut it down after. Because what I have heard pyautogui works be getting the mouse location, but what if it cant because the mouse isnt captured yet.

@BhaskarPanja93

**Comment by KevinGeLe** [comment]
> > > @KevinGeLe Is this loop issue before today's commit or after? Good luck with your payout, hopefully everything works.
> > 
> > 
> > Its after it gets one view 3 minutes in on the dashboard, it is stuck that way, but then restarts at around 8-9 minute mark. (I have also tried on another computer), also a few times the clear history doesnt have time enough to clear.
> > EDIT: I had to delete the files on the vm and then let it get them again and now it doesnt restart after 5 minutes of doing a view/nothing. But even on first start 50/50 Chrome_blank and Chrome_restore is both false and it just waits till restart.
> > If adding so that Chrome_blank and Chrome_restore needs to be true before continuing will make sure, that chrome was opened and ready perform the view, instead of just continue the viewing if it havent even went onto ngrok to get the Linkvertise link.
> > New edit: [And all my screenshot cant be uploaded for some reason](https://ibb.co/3SGLxWt)
> > @BhaskarPanja93
> 
> Stupidity hit me hard. I have to have the vm window open, because the mouse wont be captured if its in headless mode. So I have to start it in headless, open the vm window, then wait till the chrome window have opened, click on the search bar and then close vm window.
> 
> Its not a fault with the code but rather the mechanics of VirtualBox, I will look into it, maybe all we need is a script that acts as a real mouse and then shut it down after. Because what I have heard pyautogui works be getting the mouse location, but what if it cant because the mouse isnt captured yet.
> 
> @BhaskarPanja93

Ignore everything I said now.

The reason why it sometimes doesnt work is because it sometimes takes longer time for chrome to start and there it doesnt capture the search field with "ctrl + l" and therefor it cant continue. Also replacing longer delay to line 155:
`def __start_chrome_forced():
        global clear_chrome, link
        system_caller('start chrome')
        sleep(randrange(10,15))
        pyautogui.hotkey('ctrl', 'l')
        sleep(0.1)
        if clear_chrome:
            link = 'chrome://settings/resetProfileSettings'
        elif not link:
            link = get_link()
        pyautogui.typewrite(link, typing_speed)
        sleep(0.1)
        pyautogui.press('enter')
        if clear_chrome:
            sleep(6)
            coordinates = __find_image_on_screen('reset settings', confidence=0.8)
            if coordinates:
                __click(coordinates)
            sleep(3)
            link = 'chrome://settings/clearBrowserData'
            pyautogui.hotkey('ctrl', 'l')
            pyautogui.typewrite(link, typing_speed)
            sleep(0.1)
            pyautogui.press('enter')
            sleep(6)
            coordinates = __find_image_on_screen('clear data', confidence=0.8)
            if coordinates:
                __click(coordinates)
                sleep(3)
`

This have enough time to wait. So that it wont skip past to quickly. Also I had to create a new Instance.py with the parameters already filled out. Or else the code I edited directly into it would be replaced when running vm_main.py. 

also I cant seem to find minSearchTime=10 If using this, we could skip the sleep() and just have it instantly click on it if it shows up within 10 seconds like here. More neat code

**Comment by KevinGeLe** [comment]
I have fixed it now, while also making sure that the tesseract gets the correct image size when the VM is running at another resolution then 1280x720. The changes will make the vm continue to Linkvertise faster. While also allowing Laggier VM's to have enough time to continue. You also need to add so it automatically clears the directories (Downloads and RecycleBin,) to vm_main.py:
`system_caller('del /s /q "%USERPROFILE%\\Downloads\\*"')
system_caller('rd /s /q "%USERPROFILE%\\$Recycle.Bin"')`

Here is the Instance.py with the fixes:
[instance.zip](https://github.com/BhaskarPanja93/View-Bot-Client/files/11137614/instance.zip)

**Comment by BhaskarPanja93** [comment]
the reason i didnt put a minSearchTime because i didnt use pytesseract for this code, pytesseract needs Tesseract to be in PATH, which in our case isnt, so i took pyteserract functions in my own code and modified the location of Tesseract binary in it. and i didnt copy the minSeachTime function in it, so i used my own sleep statements, which is almost same. Next update i will integrate this function inside the __find_image_on_screen() function, but the problem with it is, if the image is not on screen, it will wait out the whole duration and waste more time, maybe i will integrate a self-learning model in the code which will know how long to wait for each image in the specific VM, it will make wait times more efficient. Am working on it.
@KevinGeLe

**Comment by BhaskarPanja93** [comment]
@KevinGeLe 
I made some changes, Wait times have been changes, for link typing and button clicking, and i also added the delete Downloads folder and Recycle bin folder to keep local storage clean. 
If the bot still has problems clicking links, just show me a video of what the bot is doing from the start, and i will fix it.

**Comment by BhaskarPanja93** [comment]
Any updates on this one? Problem persists or no?
@KevinGeLe

**Comment by KevinGeLe** [comment]
The problem have been fixed, thanks. Sorry for not responding, but I have lived on trains the past couple of days.

**Comment by DartMouthWrld** [comment]
@KevinGeLe How do I make sure that Chrome_blank and Chrome_restore are rue because mine are always false and the script just loops till restart?

**Comment by KevinGeLe** [comment]
> @KevinGeLe How do I make sure that Chrome_blank and Chrome_restore are rue because mine are always false and the script just loops till restart?

It sounds like your vm is just very VERY slow. Have you enabled virtualization in the BIOS? Also make sure that you have allocated 2 vCPUs to the vm's. Instead of the default 1. I run 2 vCPUs and 892 MB of ram with MemReduct installed on the vm's.

**Comment by DartMouthWrld** [comment]
> > @KevinGeLe How do I make sure that Chrome_blank and Chrome_restore are rue because mine are always false and the script just loops till restart?
> 
> It sounds like your vm is just very VERY slow. Have you enabled virtualization in the BIOS? Also make sure that you have allocated 2 vCPUs to the vm's. Instead of the default 1. I run 2 vCPUs and 892 MB of ram with MemReduct installed on the vm's.

I'll try using your config. What about the cookies popup, can the bot get past it too? @KevinGeLe

**Comment by DartMouthWrld** [comment]
@KevinGeLe Everytime memreduct runs, the bot seems to stop functioning, as if it was stopped too. How can I avoid this?
