### ISSUE TITLE
Help me pls

### ISSUE THREAD

**Issue by zagegng** [BhaskarPanja93/View-Bot-Client#38]
I have a problem, when i login to the management page where i should add ID etc, it simply doesnt load 
![problema](https://user-images.githubusercontent.com/129573953/229964634-459afc9a-8a35-4fca-8c2e-945c858490ee.png)
And this is what shows in the console

**Comment by BhaskarPanja93** [comment]
Yes i am aware of this issue when sometimes the page freezes, i will release a fix in 1-2 days, please wait till then, or you can keep hitting refresh and try your luck.

**Comment by KevinGeLe** [comment]
> Yes i am aware of this issue when sometimes the page freezes, i will release a fix in 1-2 days, please wait till then, or you can keep hitting refresh and try your luck.

I cant start the client.

`Creating Host Connection
Traceback (most recent call last):
  File "user_host.py", line 1560, in <module>
  File "user_host.py", line 226, in global_host_peering_authenticator
IndexError: index out of range
[3892] Failed to execute script 'user_host' due to unhandled exception!`

**Comment by BhaskarPanja93** [comment]
@KevinGeLe it was caused most probably because the user_host file closed while download was in progress.
Try deleting the file `C:\viewbot_files\version` and it should work, let me know if it still doesn't fix.

**Comment by BhaskarPanja93** [comment]
@zagegng 
This is a repeat for #28

**Comment by zagegng** [comment]
So if i refresh it lets say one out of a hundred, i will log in succesfully?

**Comment by zagegng** [comment]
> Yes i am aware of this issue when sometimes the page freezes, i will release a fix in 1-2 days, please wait till then, or you can keep hitting refresh and try your luck.

have you released it yet?

**Comment by BhaskarPanja93** [comment]
@zagegng sorry i lot busy this week, i will rush and try to finish this, sorry for the inconvenience. Give me some more days.  Or if you can't use it at all, ping me on <a href="https://www.instagram.com/bhaskar._.panja/">Instagram</a> and i will manually do those for you

**Comment by BhaskarPanja93** [comment]
Duplicate: #28 
Please follow instructions there
@KevinGeLe @zagegng
