### ISSUE TITLE
new captcha

### ISSUE THREAD

**Issue by softmachine1** [BhaskarPanja93/View-Bot-Client#39]
Hi,
I get this new type of captcha when I click on linkvertise links, that cannot be solved by Buster. Do you still have captchas type "recaptcha" ? 

![image](https://user-images.githubusercontent.com/125776557/230721423-395a3748-abf0-4f55-a754-8907a0cc4bc8.png)

**Comment by KevinGeLe** [comment]
Please use the updated vm_main.py code :D

**Comment by SiisMax999** [comment]
> Please use the updated vm_main.py code :D

send me a link pro

**Comment by BhaskarPanja93** [comment]
@softmachine1  Yes the new code has technique to solve these captchas (provided by @KevinGeLe). And the code is supposed to auto update too, so most probably your VM is auto updated, and it can solve these captchas by default.

also @SiisMax999 check the videos on how to make your own VM here: https://github.com/BhaskarPanja93/View-Bot-Client
you will have the new code from there on automatically.

**Comment by softmachine1** [comment]
okay  thank you
