### ISSUE TITLE
Can I run bot in cloud? And which provider allows a vm inside a vm?

### ISSUE THREAD

**Issue by DartMouthWrld** [BhaskarPanja93/View-Bot-Client#40]

**Comment by BhaskarPanja93** [comment]
@qwakup2314 
As of now you cant run this in cloud. Because you need a host machine for running the user_host file (it has to be available in network).

But i will think about this, and maybe add some techniques in the future.

**Comment by DartMouthWrld** [comment]
Alright thanks
