### ISSUE TITLE
How do I create the username and password for vm_main.py file? I can't login...!

### ISSUE THREAD

**Issue by DartMouthWrld** [BhaskarPanja93/View-Bot-Client#42]

**Comment by BhaskarPanja93** [comment]
I am really sorry for the inconvenience, please wait till i release the new data exchange technique, if you are in a rush, please text me on <a href="https://www.instagram.com/bhaskar._.panja/" > Instagram </a> and i will manually make your accounts.

**Comment by BhaskarPanja93** [comment]
#28 This is the same issue, i will post future updates regarding this issue there
