### ISSUE TITLE
stuck on chrome page

### ISSUE THREAD

**Issue by softmachine1** [BhaskarPanja93/View-Bot-Client#45]
Hi, 

When I start the bot, after the connexion to windscribe, I have this error 'the process "chome.exe" not found', then, it goes to that page and get stuck here. 

![1](https://user-images.githubusercontent.com/125776557/230779200-52ddd58d-0d9d-4fd6-90eb-0cdd2c73e6f6.png)

![2](https://user-images.githubusercontent.com/125776557/230779202-b0df54ad-ce8c-42d6-a3aa-470cf5393471.png)

**Comment by softmachine1** [comment]
(Also there are other websites such as clictune where it may be possible to do similar projects, if you are interested)

**Comment by KevinGeLe** [comment]
This almost definitely because of your keyboard layout, I had the same problem using Danish keyboard layout. The ":" is replaced with "/". Also the chrome.exe not found is nothing you should worry about. Hope it helps  :D 

@softmachine1

**Comment by BhaskarPanja93** [comment]
@KevinGeLe  is correct about this, the "chrome.exe" not found is nothing, its normal. and the webpage not found is because of the ":" replaced with "/", try to stop the code in the VM and set the keyboard layout to ENglish, it wont matter to you anyways.
@softmachine1

**Comment by softmachine1** [comment]
thank you
