### ISSUE TITLE
New site, have you tried it?

### ISSUE THREAD

**Issue by SiisMax999** [BhaskarPanja93/View-Bot-Client#47]
https://www.youtube.com/results?search_query=work.ink

https://dashboard.work.ink/

**Comment by KevinGeLe** [comment]
I will try it out. But the RPM is going to be way lower.

**Comment by BhaskarPanja93** [comment]
Will be having a vacation in a month, maybe i'll make more bots for other click to earn sites. it will be fun.
@SiisMax999 @KevinGeLe
