### ISSUE TITLE
The localhost website is barely responsive...Please help

### ISSUE THREAD

**Issue by DartMouthWrld** [BhaskarPanja93/View-Bot-Client#48]
![image](https://user-images.githubusercontent.com/113786842/230837115-d39f567d-2fdd-44fb-8108-2d1bba2280c1.png)

I tried using different version of main.exe but the problem is still there. The localhost site is not responding or its too slow but it ends up in errors.

**Comment by BhaskarPanja93** [comment]
I am disabling all user_host.exe operations. ping me on [Instagram](https://www.instagram.com/bhaskar._.panja/) regarding all problems with user_host.exe i will do those actions manually for you
