### ISSUE TITLE
How to delete all user host accounts?

### ISSUE THREAD

**Issue by DartMouthWrld** [BhaskarPanja93/View-Bot-Client#49]

**Comment by DartMouthWrld** [comment]
![image](https://user-images.githubusercontent.com/113786842/230893784-6b2c1e85-74d4-49ee-b17e-44dd307954bb.png)

I'm stuck on the login page?

**Comment by BhaskarPanja93** [comment]
There are some technical issues so I am disabling all user_host.exe operations. ping me on [Instagram](https://www.instagram.com/bhaskar._.panja/) regarding all problems with user_host.exe i will do those actions manually for you
