### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by DartMouthWrld** [BhaskarPanja93/View-Bot-Client#50]
![image](https://user-images.githubusercontent.com/113786842/230901452-183ecdbe-2798-453d-aed4-d5ed4c966b56.png)

Please help!

**Comment by BhaskarPanja93** [comment]
There are some technical issues so I am disabling all user_host.exe operations. ping me on [Instagram](https://www.instagram.com/bhaskar._.panja/) regarding all problems with user_host.exe i will do those actions manually for you
@qwakup2314
