### ISSUE TITLE
ReadTimeout Connection Error!

### ISSUE THREAD

**Issue by DartMouthWrld** [BhaskarPanja93/View-Bot-Client#51]
![image](https://user-images.githubusercontent.com/113786842/230977066-39bb1d83-80aa-417c-85cf-028f812b5331.png)

**Comment by BhaskarPanja93** [comment]
Moving server to US (Ohio) was a bad idea, i will move it to AP(Singapore), it should fix most of the issues
fixed:#51

**Comment by DartMouthWrld** [comment]
Checking user host main version...
Retrying... : ZeroDivisionError()


Checking user host main version...
Retrying... : ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='d4c3-103-27-2-141.ngrok-free.app', port=443): Read timed out. (read timeout=15)"))


Checking user host main version...
Retrying... : ZeroDivisionError()


Checking user host main version...
Retrying... : ZeroDivisionError()


Checking user host main version...
Retrying... : ZeroDivisionError()

**Comment by DartMouthWrld** [comment]
Still getting the error as of 12:00 UTC +2
