### ISSUE TITLE
Retrying... : ZeroDivisionError() -- Pls help

### ISSUE THREAD

**Issue by DartMouthWrld** [BhaskarPanja93/View-Bot-Client#55]
![image](https://user-images.githubusercontent.com/113786842/232245570-4e6d2307-c7e8-4c4b-b623-8ea028ab6ac2.png)

**Comment by Blunek** [comment]
same 
![image](https://user-images.githubusercontent.com/89209376/232247879-421085b3-aeae-4cf3-8f75-29465313e97b.png)

**Comment by DartMouthWrld** [comment]
@BhaskarPanja93 Please assist

**Comment by BhaskarPanja93** [comment]
I intentionally made the ZeroDivisionError(), this means the ngrok account is overloaded, just wait 120 seconds, and try again, it will work normally. Also i am changing the server code right now, adding the new connection technique. I know it has bugs, but it will have lesser problems(i suppose).
@Blunek @DartMouthWrld

**Comment by DartMouthWrld** [comment]
Alright, thanks for the update.

**Comment by DartMouthWrld** [comment]
@BhaskarPanja93 The ngrok server is getting overloaded again, can't everyone just use their own ngrok account if its a token issue?
