### ISSUE TITLE
I have some issues

### ISSUE THREAD

**Issue by zjt18263412280** [BhaskarPanja93/View-Bot-Client#58]
Checking user host main version...
Retrying... : ZeroDivisionError()
Unable to connect to GitHub : ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=15)"))

**Comment by KevinGeLe** [comment]
The ngrok links havent been updated.

**Comment by zjt18263412280** [comment]
> ngrok 链接尚未更新。

how often is it updated

**Comment by Luskafe** [comment]
> The ngrok links havent been updated.

kevin you on rn?

**Comment by zjt18263412280** [comment]
![1682509824267](https://user-images.githubusercontent.com/114401745/234566339-635ab23c-81d4-48aa-b7f1-f1948fea1687.png)
what should i do

**Comment by zjt18263412280** [comment]
flashback when connecting to the host

**Comment by DartMouthWrld** [comment]
@KevinGeLe Is bot working? Mine is not clicking @Luskafe @zjt18263412280 @BhaskarPanja93

**Comment by zjt18263412280** [comment]
Flashback when creating host connection
![闪退](https://user-images.githubusercontent.com/114401745/236361789-52458882-8a80-4ea0-93db-94236f229dc4.png)

**Comment by DartMouthWrld** [comment]
@zjt18263412280 Is yours stuck there? Try restarting your physical computer...

**Comment by zjt18263412280** [comment]
> @zjt18263412280 Is yours stuck there? Try restarting your physical computer...
I delete the viewbot_ Files, after downloading again, it can run normally

**Comment by DartMouthWrld** [comment]
@zjt18263412280 Are you able to login to the server and is the bot working properly as of 05/05/2023?

**Comment by BhaskarPanja93** [comment]
Duplicate: #28 
Please follow instructions there
@Luskafe @zjt18263412280 @KevinGeLe @DartMouthWrld
