### ISSUE TITLE
500 Error Server Login

### ISSUE THREAD

**Issue by DartMouthWrld** [BhaskarPanja93/View-Bot-Client#62]
![image](https://user-images.githubusercontent.com/113786842/236287327-133fc21d-69e1-4d22-a522-4867984b67a7.png)

Cannot login to server for past 24hrs please assist @BhaskarPanja93

**Comment by BhaskarPanja93** [comment]
@DartMouthWrld give me 48 hours, i will push a hotfix for login and register related issues.

**Comment by DartMouthWrld** [comment]
And bot is not running properly, its not clicking on anything in the vm, its just pasting the links.

**Comment by BhaskarPanja93** [comment]
Duplicate: #28
Please follow instructions there
@DartMouthWrld
